; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -DMQTT_MAX_PACKET_SIZE=512
lib_deps = 
	mfurga/cc1101@^1.2.0
  knolleary/PubSubClient@^2.8

; Generate compile_commands.json in project root
extra_scripts = post:extra_script.py

lib_ignore = RPAsyncTCP

; ---------- iRange Remote ----------
[env:remote_irange]
build_flags =
  -DREMOTE_PROFILE_IRANGE

; ---------- Non iRange Remote ----------
[env:remote_non_irange]
build_flags =
  -DREMOTE_PROFILE_NON_IRANGE
